---
apiVersion: apps/v1
kind: Deployment

metadata:

metadata: # Блок метаданных деплоя

  name: ui
  labels:
    app: reddit
    component: ui
spec:
  replicas: 2

  selector:
    matchLabels:
      app: reddit
      component: ui

  template: # Блок описания POD-ов

    metadata:
      name: ui-pod
      labels:
        app: reddit
        component: ui
    spec:
      containers:

      - image: kowashi/ui
        name: ui
        env:
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

      - image: snailsly/ui # Не забудьте подставить свой образ
        name: ui
